### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by masterhacka** [MrTigreroux/TigerReports#100]
[22:31:03 ERROR]: Error occurred while enabling TigerReportsSupports v1.6.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:275) ~[TigerReportsSupports.jar:?]
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:248) ~[TigerReportsSupports.jar:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1931) ~[TigerReportsSupports.jar:?]
        at fr.mrtigreroux.tigerreportssupports.bots.DiscordBot.connect(DiscordBot.java:49) ~[TigerReportsSupports.jar:?]
        at fr.mrtigreroux.tigerreportssupports.TigerReportsSupports.onEnable(TigerReportsSupports.java:75) ~[TigerReportsSupports.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.mcnative.runtime.bukkit.plugin.McNativePluginWrapperLoader.enablePlugin(McNativePluginWrapperLoader.java:138) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at net.pretronic.libraries.logging.bridge.slf4j.SLF4JBridgeServiceProvider.getMDCAdapter(SLF4JBridgeServiceProvider.java:69) ~[?:?]
        at org.slf4j.MDC.<clinit>(MDC.java:91) ~[slf4j-api-1.8.0-beta4.jar:1.8.0-beta4]
        ... 17 more

**Comment by MrTigreroux** [comment]
Thank you for reporting the issue, I think that the Discord API has been updated and therefore JDA API must be updated too. Will try to fix the issue.
