### ISSUE TITLE
WaterFall Error Loading TigerReports

### ISSUE THREAD

**Issue by FootClick** [MrTigreroux/TigerReports#101]
[23:45:58 WARN]: Error loading plugin TigerReports
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_322]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_322]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_322]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_322]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_322]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_322]
        ... 13 more

**Comment by MrTigreroux** [comment]
TigerReports must be installed on your Spigot servers, not on your BungeeCord server.
