### ISSUE TITLE
TigerReportSuport bug

### ISSUE THREAD

**Issue by bosszepro** [MrTigreroux/TigerReports#102]
I don't know why it say that

Could not load 'plugins/TigerReportsSupports.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_282]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_282]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_282]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_282]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_282]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[server.jar:git-Spigot-db6de12-18fbb24]

**Comment by MrTigreroux** [comment]
Download again TigerReportsSupports and install it following the instructions.
That error message means that you modified a file that you should not modify.
