### ISSUE TITLE
Issue with /reports

### ISSUE THREAD

**Issue by SiriHackYT** [MrTigreroux/TigerReports#115]
All works but when i use /reports to see the list of all reports, the gui is empty, no reports, but archived works ???
No error, nothing in console

**Comment by SiriHackYT** [comment]
It's only work on one spigot server, like DB doesn't work wtf

**Comment by SiriHackYT** [comment]
```
[17:25:11] [Server thread/ERROR]: Cannot load plugins/TigerReports/messages.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
 in 'string', line 2, column 3:
      Reload: "&7[&6TigerReports&7] &e ... 
      ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 35, column 5:
        Text: "&7[&6Reports&7] &eVeuille ... 
        ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-TacoSpigot-unknown]
	at fr.mrtigreroux.tigerreports.data.config.ConfigFile.load(ConfigFile.java:33) [TigerReports.jar:?]
	at fr.mrtigreroux.tigerreports.TigerReports.load(TigerReports.java:81) [TigerReports.jar:?]
	at fr.mrtigreroux.tigerreports.TigerReports.onEnable(TigerReports.java:67) [TigerReports.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352) [spigot.jar:git-TacoSpigot-unknown]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311) [spigot.jar:git-TacoSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:419) [spigot.jar:git-TacoSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:383) [spigot.jar:git-TacoSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java) [spigot.jar:git-TacoSpigot-unknown]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-TacoSpigot-unknown]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:581) [spigot.jar:git-TacoSpigot-unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'string', line 2, column 3:
      Reload: "&7[&6TigerReports&7] &e ... 
      ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 35, column 5:
        Text: "&7[&6Reports&7] &eVeuille ... 
        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[slimeworldmanager-classmodifier-2.2.1.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-TacoSpigot-unknown]
	... 17 more
```

I used your website

**Comment by SiriHackYT** [comment]
Update, same problem with default message and no error in messages.yml

**Comment by MrTigreroux** [comment]
Could you download and put that file [logs.config.txt](https://github.com/MrTigreroux/TigerReports/files/8709937/logs.config.txt) in your `plugins/TigerReports` folder and rename it to `logs.config`. Then restart your Spigot server and try to open the menu with /reports and if it doesn't display anything, wait for 10 seconds, then if it still doesn't display anything, close it, stop your server and send me all the logs starting from "[TigerReports] Enabling..." until "[TigerReports] Disabling..." hiding sensitive data (IP, ...) (you can send that file in SpigotMC private message if you want).
Thank you in advance.


 

> Update, same problem with default message and no error in messages.yml

I'm sorry but I don't understand what you mean, do you mean that the messages you configured are not displayed in game ? If so, what Minecraft version do your server run and in what format did you encode the messages.yml file ?

**Comment by MrTigreroux** [comment]
The problem has been fixed in the [version 5.0.16](https://www.spigotmc.org/resources/tigerreports.25773/update?update=456720). Thank you for reporting it.
