### ISSUE TITLE
Data too long for column

### ISSUE THREAD

**Issue by SiriHackYT** [MrTigreroux/TigerReports#125]
![image](https://user-images.githubusercontent.com/49961233/193795479-ab9e4e5b-f6c9-4384-b727-87ffb04a8538.png)

Error when i click on Update in 5.1

**Comment by MrTigreroux** [comment]
Could you run that MySQL query (in phpMyAdmin for example follow [that tutorial](https://github.com/MrTigreroux/TigerReports/wiki/Run-a-SQL-query-on-a-MySQL-database)) and give me the result please ?
`SELECT reporter_ip,MAX(LENGTH(reporter_ip)) FROM tigerreports_reports`

**Comment by SiriHackYT** [comment]
![image](https://user-images.githubusercontent.com/49961233/193810374-5b6de1e6-dabc-44b3-8951-f625c3ec1612.png)

**Comment by SiriHackYT** [comment]
Result : 
nwcsnbsc03w-XX-XX-XXX-XX.dhcp-dynamic.fibreop.nb.bellaliant.net/XX.XX.XXX.XX

**Comment by MrTigreroux** [comment]
Ok thank you, the error comes from the way I'm getting the player IP which isn't standard.
Anyway, just run that 2 queries and all should work:
ALTER TABLE tigerreports_reports MODIFY reporter_ip VARCHAR(250);
ALTER TABLE tigerreports_reports MODIFY reported_ip VARCHAR(250)

**Comment by SiriHackYT** [comment]
Same error after the alter table, maybe your new version put a varchar ?

**Comment by MrTigreroux** [comment]
I don't understand, can I see the error and what you did before it please ?

**Comment by SiriHackYT** [comment]
![image](https://user-images.githubusercontent.com/49961233/193815743-93dab013-8450-40d3-a384-203a01a82778.png)
Après avoir cliqué ici, j'ai cette erreur qui apparait en console : 
![image](https://user-images.githubusercontent.com/49961233/193815945-72ff4cc5-ca6d-4442-9c95-6760adb22f05.png)

**Comment by SiriHackYT** [comment]
That's good

**Comment by MrTigreroux** [comment]
I think that you have not updated TigerReports on all your Spigot server to the last 5.1 version.

**Comment by SiriHackYT** [comment]
All is update on all server, the message is not shown in reports and i have this error when a player want to report
`[17:17:16] [Craft Scheduler Thread - 558/ERROR]: [TigerReports] Une erreur est survenue avec la base de donnees:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''reported_location'='BedWars4v4-1/horloge_copy/3.65/140.0/-13.83/-219.03/25.6...' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_331]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_331]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_331]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_331]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at fr.mrtigreroux.tigerreports.data.database.Database.update(Database.java:127) ~[?:?]
	at fr.mrtigreroux.tigerreports.data.database.Database.lambda$updateAsynchronously$7(Database.java:115) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_331]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_331]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_331]`

**Comment by SiriHackYT** [comment]
And antoher error on all my servers 
![image](https://user-images.githubusercontent.com/49961233/194590036-f37569e1-cfdd-4e14-953b-ea23644ec5fd.png)

**Comment by MrTigreroux** [comment]
Thank you for reporting that errors.
Do you have a world named "horloge_copy" in your server BedWars4v4-1 ? (I ask that because the name seems weird).
The first error should be fixed with the new [5.1.1 version](https://www.spigotmc.org/resources/tigerreports.25773/update?update=475485). But the second is really strange, I added a check but I'm not sure it will fix it.

**Comment by SiriHackYT** [comment]
Yes is that, i put this version and i check it

**Comment by SiriHackYT** [comment]
![image](https://user-images.githubusercontent.com/49961233/194756872-6ba4a451-3e73-43d9-8526-077b7c03d9df.png)
Only just this error now

**Comment by MrTigreroux** [comment]
Ok, this error is strange because it implies that your BungeeCord server doesn't send a valid message. Do you have any BungeeCord plugin ? Do you have any special BungeeCord proxy server configuration ?
Please try on a Spigot server to put that file [logs.config.txt](https://github.com/MrTigreroux/TigerReports/files/9741928/logs.config.txt) in your plugins/TigerReports folder, rename it to `logs.config` then restart your server, wait for the error to appear in the console/logs and then send me all the logs starting from "[TigerReports] Enabling ..." (removing any sensitive information like IPs).

**Comment by MrTigreroux** [comment]
If you still have this error, it would really help me if you could do what I asked in my previous message.
For now, I close that issue assuming you no longer have that error.
