### ISSUE TITLE
Console spam with errors

### ISSUE THREAD

**Issue by Miriam0** [MrTigreroux/TigerReports#127]
java.lang.NullPointerException: Cannot invoke "fr.mrtigreroux.tigerreports.objects.users.User.getOpenedMenu()" because "u" is null
	at fr.mrtigreroux.tigerreports.listeners.InventoryListener.checkMenuAction(InventoryListener.java:82) ~[TigerReports.jar:?]
	at fr.mrtigreroux.tigerreports.listeners.InventoryListener.onInventoryClick(InventoryListener.java:46) ~[TigerReports.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:MultiPaper-1.19.2-37]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3359) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at puregero.multipaper.externalserverprotocol.PlayerActionPacket.lambda$handle$0(PlayerActionPacket.java:63) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:53:23] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TigerReports v5.1.2
java.lang.NullPointerException: Cannot invoke "fr.mrtigreroux.tigerreports.objects.users.User.getOpenedMenu()" because "u" is null
	at fr.mrtigreroux.tigerreports.listeners.InventoryListener.checkMenuAction(InventoryListener.java:82) ~[TigerReports.jar:?]
	at fr.mrtigreroux.tigerreports.listeners.InventoryListener.onInventoryClick(InventoryListener.java:46) ~[TigerReports.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:MultiPaper-1.19.2-37]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3359) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at puregero.multipaper.externalserverprotocol.PlayerActionPacket.lambda$handle$0(PlayerActionPacket.java:63) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:53:23] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TigerReports v5.1.2
java.lang.NullPointerException: Cannot invoke "fr.mrtigreroux.tigerreports.objects.users.User.getOpenedMenu()" because "u" is null
	at fr.mrtigreroux.tigerreports.listeners.InventoryListener.checkMenuAction(InventoryListener.java:82) ~[TigerReports.jar:?]
	at fr.mrtigreroux.tigerreports.listeners.InventoryListener.onInventoryClick(InventoryListener.java:46) ~[TigerReports.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:MultiPaper-1.19.2-37]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[MultiPaper-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3359) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at puregero.multipaper.externalserverprotocol.PlayerActionPacket.lambda$handle$0(PlayerActionPacket.java:63) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MrTigreroux** [comment]
Hello, thank you for reporting this issue.
I think that the problem comes from the fact that you use "MultiPaper". I could of course remove the error but it will probably not fix the issue.
Because MultiPaper requires a special configuration (several servers, players...), I can't test it by myself. Therefore I would need more logs, and for that I need you to:
* Stop your server
* Download that file: [logs.config.txt](https://github.com/MrTigreroux/TigerReports/files/10201656/logs.config.txt) and put it in the `plugins/TigerReports` of your server(s?)
* Rename the previous file to "logs.config"
* Restart your server
* Wait for the error to appear again in the console (you can probably trigger it by opening `/reports` menu)
* Copy all logs from "[TigerReports] Enabling..." to the error and send them (hidding sensitive information like IPs) to me here or in [private message](https://www.spigotmc.org/conversations/add?to=MrTigreroux) on SpigotMC forum.
Thank you in advance.
