### ISSUE TITLE
Issue when trying to report someone who is not online

### ISSUE THREAD

**Issue by lionsavage** [MrTigreroux/TigerReports#130]
When trying to report someone who is not in the server, I receive this error message. No sure why, but just wanted to report it :)

[17:23:24 WARN]: [TigerReports] Plugin TigerReports v5.1.3 generated an exception while executing task 22968
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
        at java.lang.String.replace(String.java:2957) ~[?:?]
        at fr.mrtigreroux.tigerreports.managers.VaultManager.getVaultDisplayName(VaultManager.java:124) ~[TigerReports (1).jar:?]
        at fr.mrtigreroux.tigerreports.managers.VaultManager.access$000(VaultManager.java:24) ~[TigerReports (1).jar:?]
        at fr.mrtigreroux.tigerreports.managers.VaultManager$1.run(VaultManager.java:100) ~[TigerReports (1).jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-431]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-431]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MrTigreroux** [comment]
Hello,
The problem should be fixed in the new [5.1.4 version](https://www.spigotmc.org/resources/tigerreports.25773/update?update=492385). Thank you again for reporting it.
Please let me know if it's not the case.
Have a good day.
