### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Chaostarts** [MrTigreroux/TigerReports#165]
Paper1.20.1
TigerReports 5.3.3

[15:18:55 ERROR]: [TigerReports] [BungeeManager] Une erreur est survenue en traitant une notification BungeeCord:
java.io.EOFException: null
        at java.io.DataInputStream.readFully(DataInputStream.java:203) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$FieldSerializer.readString(BungeeNotificationType.java:447) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$FieldSerializer.access$300(BungeeNotificationType.java:200) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$FieldSerializer$8.read(BungeeNotificationType.java:373) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$NotificationDataField.read(BungeeNotificationType.java:187) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType.readNotification(BungeeNotificationType.java:503) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.BungeeManager.onPluginMessageReceived(BungeeManager.java:602) ~[TigerReports.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3612) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1385) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:18:55 ERROR]: [TigerReports] [BungeeManager] Une erreur est survenue en traitant une notification BungeeCord:
java.io.EOFException: null
        at java.io.DataInputStream.readFully(DataInputStream.java:203) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$FieldSerializer.readString(BungeeNotificationType.java:447) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$FieldSerializer.access$300(BungeeNotificationType.java:200) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$FieldSerializer$8.read(BungeeNotificationType.java:373) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType$NotificationDataField.read(BungeeNotificationType.java:187) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.notifications.BungeeNotificationType.readNotification(BungeeNotificationType.java:503) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.bungee.BungeeManager.onPluginMessageReceived(BungeeManager.java:602) ~[TigerReports.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3612) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1385) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MrTigreroux** [comment]
Hello, I think that you have a BungeeCord network on which 1 or more Spigot servers have a different version of TigerReports than the 5.3.3.
When you find and fix it, do not forget to restart your BungeeCord network.
