### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Farosdos** [MrTigreroux/TigerReports#168]
Plugin version: 5.3.5
Server version: papermc 1.16.5
Java version: 17
Error:
[15:20:53] [Server thread/INFO]: [TigerReports] Enabling TigerReports v5.3.5
[15:20:53] [Server thread/ERROR]: Error occurred while enabling TigerReports v5.3.5 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'confıg.yml' cannot be found in plugins\TigerReports.jar
	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:192) ~[patched_1.16.5.jar:git-Paper-790]
	at fr.mrtigreroux.tigerreports.data.config.ConfigFile.reset(ConfigFile.java:73) ~[?:?]
	at fr.mrtigreroux.tigerreports.data.config.ConfigFile.load(ConfigFile.java:32) ~[?:?]
	at fr.mrtigreroux.tigerreports.TigerReports.load(TigerReports.java:90) ~[?:?]
	at fr.mrtigreroux.tigerreports.TigerReports.onEnable(TigerReports.java:84) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Thread.java:842) [?:?]
[15:20:53] [Server thread/INFO]: [TigerReports] Disabling TigerReports v5.3.5

**Comment by MrTigreroux** [comment]
Hello, it seems that your TigerReports.jar file is corrupted, try to download it again from https://www.spigotmc.org/resources/tigerreports.25773/, and restart your server.
