### ISSUE TITLE
Multiple menu items not working

### ISSUE THREAD

**Issue by piotrskibapl** [MrTigreroux/TigerReports#58]
Hi,

It looks like after the recent update (4.12.6) the archived reports GUI button doesn't work.

I get an error in console after using it:
```
[17:24:47] [Server thread/ERROR]: Could not pass event InventoryClickEvent to TigerReports v4.12.6
java.lang.NoClassDefFoundError: fr/mrtigreroux/tigerreports/objects/menus/ArchivedReportsMenu
at fr.mrtigreroux.tigerreports.objects.users.OnlineUser.openArchivedReportsMenu(OnlineUser.java:124) ~[?:?]
at fr.mrtigreroux.tigerreports.objects.menus.ReportsMenu.onClick(ReportsMenu.java:47) ~[?:?]
at fr.mrtigreroux.tigerreports.objects.menus.Menu.click(Menu.java:143) ~[?:?]
at fr.mrtigreroux.tigerreports.listeners.InventoryListener.onInventoryClick(InventoryListener.java:40) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-582]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-582]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-582]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2687) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-582]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-582]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by piotrskibapl** [comment]
Update: looks like this is also present for deleting reports, accessing report comments and closing the report (with the barrier button at the bottom of GUI)

**Comment by MrTigreroux** [comment]
Hello,
The error you get is "NoClassDefFoundError" which may be caused by a modification of the jar. Try to download and install the latest version of TigerReports, stopping your server before, and the problem should be fixed.

**Comment by piotrskibapl** [comment]
Looks like the plugin for some reason wasn't properly loaded. After restarting the server it works fine, sorry for taking your time, and thanks for the help!

**Comment by MrTigreroux** [comment]
Yes, this can be induced by the use of plugins like plugman.
