### ISSUE TITLE
Server exception

### ISSUE THREAD

**Issue by galexrt** [MrTigreroux/TigerReports#65]
Hey, I'm not sure if this is actually an issue with TigerReports or a Paper issue.

I wanted to raise it here first as the server crashed just after the `/report` command was used.

This is with Paper 1.16.5 build 692, OpenJDK Java 11.0.11.

```
[23:01:16 INFO]: Mexi16 issued server command: /report Frostzzboii Test für Frostiboi
[23:01:16 ERROR]: Encountered an unexpected exception
survival-0 paper java.lang.NoClassDefFoundError: Could not initialize class com.destroystokyo.paper.event.server.ServerExceptionEvent
survival-0 paper 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:812) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2176) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-693]
survival-0 paper 	at java.lang.Thread.run(Thread.java:829) [?:?]
[23:01:16 ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2021-05-19_23.01.16-server.txt
```

Please let me know if you need the full crash report, if this is the wrong place and / or this seems to be a Paper related issue.

Thanks!

**Comment by MrTigreroux** [comment]
Hello, did you try to type another time the same command ? Does it make the server crash again ?
Did you try to use `/tigerreports:report` command to be sure that the command is the one of TigerReports ?
Maybe the problem comes from the special character `ü`, did you try to use it in another command/message in chat ?

To what I can understand, the problem seems to be a bad loading of Paper (a class is not loaded), restarting (not with `/reload`) your server should fix the issue. If the issue is still there, try to use another version of Paper.
But from what I see, there is no direct link with TigerReports.

**Comment by galexrt** [comment]
Hey, I found out yesterday's night and forgot to update the ticket.

The issue was that I had an alias setup from some time ago on that server for `/report` pointing to another command and seems that Paper doesn't like that for obvious reasons :D

`commands.yml`:

```
aliases:
[...]
-    report:
+    ticket:
     - "report $1-"
```

Sorry about that, though maybe this can help someone in the future that may has an alias for an existing command like this scenario.

Thanks for the quick response!
