### ISSUE TITLE
BungeeCord error

### ISSUE THREAD

**Issue by craciu25yt** [MrTigreroux/TigerReports#70]
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:75) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[server.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:80bfedf:416]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 13 more

**Comment by MrTigreroux** [comment]
Please read the Installation section of the presentation page of the plugin.
TigerReports isn't a BungeeCord plugin, it is a Spigot plugin which can interact with BungeeCord.
