### ISSUE TITLE
Problem changing the language to Spanish

### ISSUE THREAD

**Issue by TheDiego845** [MrTigreroux/TigerReports#85]
[13:13:18 ERROR]: Cannot load plugins/TigerReports/messages.yml
org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found '<block mapping start>'
 in 'string', line 38, column 1:
    ErrorMessages:
    ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.17.1.jar:git-Paper-255]
        at fr.mrtigreroux.tigerreports.data.config.ConfigFile.load(ConfigFile.java:35) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.TigerReports.load(TigerReports.java:47) ~[TigerReports.jar:?]
        at fr.mrtigreroux.tigerreports.commands.ReportsCommand.onCommand(ReportsCommand.java:52) ~[TigerReports.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-255]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-255]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<block mapping start>'
 in 'string', line 38, column 1:
    ErrorMessages:
    ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:256) ~[patched_1.17.1.jar:git-Paper-255]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[patched_1.17.1.jar:git-Paper-255]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:155) ~[patched_1.17.1.jar:git-Paper-255]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:149) ~[patched_1.17.1.jar:git-Paper-255]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[patched_1.17.1.jar:git-Paper-255]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.17.1.jar:git-Paper-255]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.17.1.jar:git-Paper-255]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.17.1.jar:git-Paper-255]
        ... 16 more

**Comment by MrTigreroux** [comment]
Could you try to delete your messages.yml file and restart your server, and check that there is no error, then copy/paste the messages from https://raw.githubusercontent.com/MrTigreroux/TigerReports/master/TigerReports/messages/spanish.yml, encode the file in ANSI if your server is in Minecraft 1.8 or lower, UTF-8 otherwise, and then reload with `/reports reload` command.
